include: ['_pages', '_css', '_scripts', '_images']

title: Battle Facilities Calculator

github: [metadata]
  
url: "https://to-metrion.github.io"
  
repository: to-metrion/to-metrion.github.io

description:
  Pokemon Damage Calculator for SwSh Battle Facilities, with Battle Tower and Restricted Sparring sets preloaded.
  

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

theme: jekyll-theme-cayman
